### ISSUE TITLE
Code availability 

### ISSUE THREAD

**Issue by fyang064** [C0notSilly/-ICCV-23-Edge-Deformation-based-Online-Augmentation#1] opened 2024-07-23 23:42 UTC
Hello author, I’m just wondering when the code will be released.

**Comment by jlluser** [comment] 2024-11-09 13:34
作者，您好！
最近读了您的“Shift from Texture-bias to Shape-bias:Edge Deformation-based Augmentation for Robust Object Recognition”这篇文章，感觉受用很多，想具体了解一下代码的实现机制，根据论文文献中的提示，代码实现放在了“https://github.com/C0notSilly/-ICCV-23-Edge-Deformation-based-Online-Augmentation”中，打开发现，里面没有内容，想咨询一下，现在代码能发出吗？

**Comment by C0notSilly** [comment] 2024-11-09 14:27
Sorry for the delay. Due to data storage issue, the code was previously lost. I will release a reproduced version after CVPR deadline in approximately two weeks.

**Comment by C0notSilly** [comment] 2024-11-09 14:27
Sorry for the delay. Due to data storage issue, the code was previously lost. I will release a reproduced version after CVPR deadline in approximately two weeks.

**Comment by C0notSilly** [comment] 2024-11-09 14:31
你好，这个代码之前数据损坏有一部分遗失了，但是比较核心的部分还在手上，如果紧急需要我可以给你发下，后续cvpr ddl结束后会在github上公开一个复现版本。



发自我的iPhone


------------------ Original ------------------
From: jlluser ***@***.***&gt;
Date: Sat,Nov 9,2024 9:35 PM
Cc: Subscribed ***@***.***&gt;
Subject: Re: [C0notSilly/-ICCV-23-Edge-Deformation-based-Online-Augmentation]Code availability  (Issue #1)





 
作者，您好！
 最近读了您的“Shift from Texture-bias to Shape-bias:Edge Deformation-based Augmentation for Robust Object Recognition”这篇文章，感觉受用很多，想具体了解一下代码的实现机制，根据论文文献中的提示，代码实现放在了“https://github.com/C0notSilly/-ICCV-23-Edge-Deformation-based-Online-Augmentation”中，打开发现，里面没有内容，想咨询一下，现在代码能发出吗？

**Comment by C0notSilly** [comment] 2024-11-09 15:14
@jlluser A rough copy of the code is now available at the master branch of this repo. Given that the code is now available, I will close this issue.

**Closed as completed** 2024-11-09 15:16 UTC

**Comment by jlluser** [comment] 2024-11-09 15:33
谢谢，感谢共享，愿你在学术上取得更好的突破性成果~
